inference_templates = {
    "painted_on_examples":[
        "cat {} stone",
        "cat {} vase",
        "hamburger {} canvas",
        "spiderman {} building",
        "michael jackson {} stone",
        "michael jackson {} wall"
    ],
    "carved_by_examples":[
        "cat {} jade",
        "cat {} clay",
        "cat {} wood",
        "rose {} carrot",
        "rose {} glass",
        "rose {} paper",
    ],
    "inside_examples":[
        "cat {} bowl",
        "cat {} box",
        "hamster {} cup",
        "hamster {} vase",
        "spiderman {} basket",
        "ocean {} pot",
    ],
    "hug_examples":[
        "cat {} dog",
        "frog {} bear",
        "Donald Trump {} Obama",
        "man {} woman",
        "monkey {} cat",
        "bear {} monkey",
    ],
    "hug_examples_v2":[
        "bear {} a monkey",
        "monkey {} a bear",
        "dog {} a cat",
        "cat {} a dog",
        "cat {} a bird",
        "lion {} a cow",
        "a photo of a bear {} a monkey",
        "a photo of a monkey {} a bear",
        "a photo of a lion {} a lion",
        "a photo of a dog {} a cat",
        "a photo of a cat {} a bird", 
    ],
    "hug_examples_v3":[
        "Yann Lecun {} Yann Lecun",
        "Hinton {} Hinton",
        "Messi {} Yann Lecun",
        "Bruno Mars {} Hinton",
        "Yao Ming {} Yao Ming",
        "Taylor Swift {} Taylor Swift",
        "Kanye West {} Messi",
        "Spiderman {} Yann Lecun",
        "Megatron {} Messi",
        "Messi {} Bruno Mars",
        "Beckham {} a Superman", 
        "A photo of Yann Lecun {} Yann Lecun",
        "A photo of Hinton {} Hinton",
        "A photo of Messi {} Yann Lecun",
        "A photo of Bruno Mars {} Hinton",
        "A photo of Yao Ming {} Yao Ming",
        "A photo of Taylor Swift {} Taylor Swift",
        "A photo of Kanye West {} Messi",
        "A photo of Spiderman {} Yann Lecun",
        "A photo of Megatron {} Messi",
        "A photo of Messi {} Bruno Mars",
        "A photo of Beckham {} a Superman", 
    ],

    "hug_examples_v4":[
        "Messi {} a big doll",
        "Bruno Mars {} a big doll",
        "Yao Ming {} a big doll",
        "Taylor Swift {} a big doll",
        "Kanye West {} a big doll",
        "Spiderman {} a big doll",
        "Megatron {} a big doll",
        "Messi {} a big doll",
        "Beckham {} a big doll",
        "Super Mario {} a big doll",
        "Kobe Bryant {} a big doll",
        "Justin Bieber {} a big doll",
        "Lady Gaga {} a big doll",
        ],

    "hug_examples_v5":[
        "Messi {} a grandpa",
        "Bruno Mars {} a grandpa",
        "Yao Ming {} a grandpa",
        "Taylor Swift {} a grandpa",
        "Kanye West {} a grandpa",
        "Spiderman {} a grandpa",
        "Megatron {} a grandpa",
        "Messi {} a grandpa",
        "Beckham {} a grandpa",
        "Super Mario {} a grandpa",
        "Kobe Bryant {} a grandpa",
        "Justin Bieber {} a grandpa",
        "Lady Gaga {} a grandpa",
        ],

    "hug_examples_v6":[
    "A photo of cat hug a cat",
    # "A photo of rabbit hug a cat",
    # "A photo of cat hug a dog",
    # "A photo of frog hug a cat",
    ],

    "reversion_bad_cases":[
    # "A photo of kangaroo {} a bottle on a table",
    # "A photo of newton {} a golf ball",
    "A photo of woman {} a dog",
    "A photo of Taylor Swift {} a wallet",
    "A photo of Shakespear {} a wallet",
    "A photo of bear {} a banana",
    ],

    "reversion_bad_cases-v2":[
    "A photo of woman {} a dog",
    "A photo of Tiger {} a golf ball",
    "A photo of man {} a cup",
    ],

    "pick_up_examples":
    [
        
        "A robot {} a strawberry",
        "A robot arm {} a strawberry",
        "A robot arm {} a strawberry on a table",
        "A robot {} a strawberry on a table",
        "A robot {} a strawberry on a table, indoor scene",
        "A robot arm {} a small strawberry on a table",
        "A robot arm {} a small strawberry on a table, indoor scene",
        "A photo of a robot {} a strawberry",
        "A photo of a robot arm {} a strawberry",
        "A photo of a robot arm {} a strawberry on a table",
        "A photo of a robot {} a strawberry on a table",
        "A photo of a robot {} a strawberry on a table, indoor scene",
        "A photo of a robot arm {} a small strawberry on a table",
        "A photo of a robot arm {} a small strawberry on a table, indoor scene",
        "An image of a robot {} a strawberry",
        "An image of a robot arm {} a strawberry",
        "An image of a robot arm {} a strawberry on a table",
        "An image of a robot {} a strawberry on a table",
        "An image of a robot {} a strawberry on a table, indoor scene",
        "An image of a robot arm {} a small strawberry on a table",
        "An image of a robot arm {} a small strawberry on a table, indoor scene",
        
        
        "A photo of a robot {} a tennis ball on a table, indoor scene",
        "A photo of a robot arm {} a tennis ball on a table, indoor scene",
        "A photo of a boy {} a tennis ball on a table, indoor scene",
        "A photo of a girl {} a tennis ball on a table, indoor scene",
        "A photo of a grandpa {} a tennis ball on a table, indoor scene",
        "A photo of a monkey {} a tennis ball on a table, indoor scene",
        "A photo of a baby {} a tennis ball on a table, indoor scene",
        "A photo of a otter {} a tennis ball on a table, indoor scene",
        "A photo of Donald Trump {} a tennis ball on a table, indoor scene",
        
        
        "A photo of a robot {} a baseball on a table, indoor scene",
        "A photo of a robot arm {} a baseball on a table, indoor scene",
        "A photo of a boy {} a baseball on a table, indoor scene",
        "A photo of a girl {} a baseball on a table, indoor scene",
        "A photo of a grandpa {} a baseball on a table, indoor scene",
        "A photo of a monkey {} a baseball on a table, indoor scene",
        "A photo of a baby {} a baseball on a table, indoor scene",
        "A photo of a otter {} a baseball on a table, indoor scene",
        "A photo of Donald Trump {} a baseball on a table, indoor scene",
        
        "A photo of a robot {} a bottle on a table, indoor scene",
        "A photo of a robot arm {} a bottle on a table, indoor scene",
        "A photo of a boy {} a bottle on a table, indoor scene",
        "A photo of a girl {} a bottle on a table, indoor scene",
        "A photo of a grandpa {} a bottle on a table, indoor scene",
        "A photo of a monkey {} a bottle on a table, indoor scene",
        "A photo of a baby {} a bottle on a table, indoor scene",
        "A photo of Donald Trump {} a bottle on a table, indoor scene",
        
        "A photo of a robot {} a lemon on a table, indoor scene",
        "A photo of a robot arm {} a lemon on a table, indoor scene",
        "A photo of a boy {} a lemon on a table, indoor scene",
        "A photo of a girl {} a lemon on a table, indoor scene",
        "A photo of a grandpa {} a lemon on a table, indoor scene",
        "A photo of a monkey {} a lemon on a table, indoor scene",
        "A photo of a baby {} a lemon on a table, indoor scene",
        "A photo of Donald Trump {} a lemon on a table, indoor scene",
        
        "A photo of a robot {} a World Cup on a table, indoor scene",
        "A photo of a robot arm {} a World Cup on a table, indoor scene",
        "A photo of a boy {} a World Cup on a table, indoor scene",
        "A photo of a girl {} a World Cup on a table, indoor scene",
        "A photo of a grandpa {} a World Cup on a table, indoor scene",
        "A photo of a monkey {} a World Cup on a table, indoor scene",
        "A photo of a baby {} a World Cup on a table, indoor scene",
        "A photo of Donald Trump {} a World Cup on a table, indoor scene",
    ],
    "simple_pickup_templates":
    [
    "A photo of a robot {} an iPhone on a table, indoor scene",
    "A photo of a robot arm {} an iPhone on a table, indoor scene",
    "A photo of a boy {} an iPhone on a table, indoor scene",
    "A photo of a girl {} an iPhone on a table, indoor scene",
    "A photo of a grandpa {} an iPhone on a table, indoor scene",
    "A photo of a monkey {} an iPhone on a table, indoor scene",
    "A photo of a baby {} an iPhone on a table, indoor scene",
    "A photo of Donald Trump {} an iPhone on a table, indoor scene",
    
    
    "A photo of a robot {} an apple on a table, indoor scene",
    "A photo of a robot arm {} an apple on a table, indoor scene",
    "A photo of a boy {} an apple on a table, indoor scene",
    "A photo of a girl {} an apple on a table, indoor scene",
    "A photo of a grandpa {} an apple on a table, indoor scene",
    "A photo of a monkey {} an apple on a table, indoor scene",
    "A photo of a baby {} an apple on a table, indoor scene",
    "A photo of Donald Trump {} an apple on a table, indoor scene",
    
    "A photo of a robot {} a bottle on a table, indoor scene",
    "A photo of a robot arm {} a bottle on a table, indoor scene",
    "A photo of a boy {} a bottle on a table, indoor scene",
    "A photo of a girl {} a bottle on a table, indoor scene",
    "A photo of a grandpa {} a bottle on a table, indoor scene",
    "A photo of a monkey {} a bottle on a table, indoor scene",
    "A photo of a baby {} a bottle on a table, indoor scene",
    "A photo of Donald Trump {} a bottle on a table, indoor scene",
    
    "A photo of a robot {} a vase on a table, indoor scene",
    "A photo of a robot arm {} a vase on a table, indoor scene",
    "A photo of a boy {} a vase on a table, indoor scene",
    "A photo of a girl {} a vase on a table, indoor scene",
    "A photo of a grandpa {} a vase on a table, indoor scene",
    "A photo of a monkey {} a vase on a table, indoor scene",
    "A photo of a baby {} a vase on a table, indoor scene",
    "A photo of Donald Trump {} a vase on a table, indoor scene",
    
    "A photo of a robot {} a trophy cup on a table, indoor scene",
    "A photo of a robot arm {} a trophy cup on a table, indoor scene",
    "A photo of a boy {} a trophy cup on a table, indoor scene",
    "A photo of a girl {} a trophy cup on a table, indoor scene",
    "A photo of a grandpa {} a trophy cup on a table, indoor scene",
    "A photo of a monkey {} a trophy cup on a table, indoor scene",
    "A photo of a baby {} a trophy cup on a table, indoor scene",
    "A photo of Donald Trump {} a trophy cup on a table, indoor scene",
    
    "A photo of a rabit {} a carrot, on the field",
    "A photo of a lady {} a sunglasses, on the beach",
    "A photo of Michael Jackson {} a ring, on a table",
    "A photo of Taylor Swift {} a wallet, on the ground",
    "A photo of a panda {} a stone, in the forest",
    "A photo of a cleaner {} a waste paper, on the ground",
    "A photo of a bird {} a cherry, on the tree",
    "A photo of a cat {} a ball of yarn, on the wooden floor",
    "A photo of a otter {} a fish, by the lake",],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],
    
    "sd-lift-templates-v1":
    ["A photo of Donald Trump lift a lemon on a table, indoor scene"],

    "sd-lift-templates":
    [
    "A photo of a robot lift an iPhone on a table, indoor scene",
    "A photo of a robot arm lift an iPhone on a table, indoor scene",
    "A photo of a boy lift an iPhone on a table, indoor scene",
    "A photo of a girl lift an iPhone on a table, indoor scene",
    "A photo of a grandpa lift an iPhone on a table, indoor scene",
    "A photo of a monkey lift an iPhone on a table, indoor scene",
    "A photo of a baby lift an iPhone on a table, indoor scene",
    "A photo of Donald Trump lift an iPhone on a table, indoor scene",
    
    
    "A photo of a robot lift an apple on a table, indoor scene",
    "A photo of a robot arm lift an apple on a table, indoor scene",
    "A photo of a boy lift an apple on a table, indoor scene",
    "A photo of a girl lift an apple on a table, indoor scene",
    "A photo of a grandpa lift an apple on a table, indoor scene",
    "A photo of a monkey lift an apple on a table, indoor scene",
    "A photo of a baby lift an apple on a table, indoor scene",
    "A photo of Donald Trump lift an apple on a table, indoor scene",
    
    "A photo of a robot lift a bottle on a table, indoor scene",
    "A photo of a robot arm lift a bottle on a table, indoor scene",
    "A photo of a boy lift a bottle on a table, indoor scene",
    "A photo of a girl lift a bottle on a table, indoor scene",
    "A photo of a grandpa lift a bottle on a table, indoor scene",
    "A photo of a monkey lift a bottle on a table, indoor scene",
    "A photo of a baby lift a bottle on a table, indoor scene",
    "A photo of Donald Trump lift a bottle on a table, indoor scene",
    
    "A photo of a robot lift a vase on a table, indoor scene",
    "A photo of a robot arm lift a vase on a table, indoor scene",
    "A photo of a boy lift a vase on a table, indoor scene",
    "A photo of a girl lift a vase on a table, indoor scene",
    "A photo of a grandpa lift a vase on a table, indoor scene",
    "A photo of a monkey lift a vase on a table, indoor scene",
    "A photo of a baby lift a vase on a table, indoor scene",
    "A photo of Donald Trump lift a vase on a table, indoor scene",
    
    "A photo of a robot lift a trophy cup on a table, indoor scene",
    "A photo of a robot arm lift a trophy cup on a table, indoor scene",
    "A photo of a boy lift a trophy cup on a table, indoor scene",
    "A photo of a girl lift a trophy cup on a table, indoor scene",
    "A photo of a grandpa lift a trophy cup on a table, indoor scene",
    "A photo of a monkey lift a trophy cup on a table, indoor scene",
    "A photo of a baby lift a trophy cup on a table, indoor scene",
    "A photo of Donald Trump lift a trophy cup on a table, indoor scene",
    
    "A photo of a rabit lift a carrot, on the field",
    "A photo of a lady lift a sunglasses, on the beach",
    "A photo of Michael Jackson lift a ring, on a table",
    "A photo of Taylor Swift lift a wallet, on the ground",
    "A photo of a panda lift a stone, in the forest",
    "A photo of a cleaner lift a waste paper, on the ground",
    "A photo of a bird lift a cherry, on the tree",
    "A photo of a cat lift a ball of yarn, on the wooden floor",
    "A photo of a otter lift a fish, by the lake",],

    "simple_pull_drawer_templates-v519":
    [
    "A photo of a boy {} a drawer of a cabinet, indoor scene",
    "A photo of a girl {} a drawer of a cabinet, indoor scene",
    "A photo of a grandpa {} a drawer of a cabinet, indoor scene",
    "A photo of a monkey {} a drawer of a cabinet, indoor scene",
    "A photo of a baby {} a drawer of a cabinet, indoor scene",
    "A photo of a bear {} a drawer of a cabinet, indoor scene",
    "A photo of a panda {} a drawer of a cabinet, indoor scene",
    "A photo of a squrrirel {} a drawer of a cabinet, indoor scene",
    "A photo of David Beckham {} a drawer of a cabinet, indoor scene",
    "A photo of Michael Jackson {} a drawer of a cabinet, indoor scene",
    "A photo of Taylor Swift {} a drawer of a cabinet, indoor scene",

    "A photo of a boy {} a drawer of a desk, indoor scene",
    "A photo of a girl {} a drawer of a desk, indoor scene",
    "A photo of a grandpa {} a drawer of a desk, indoor scene",
    "A photo of a monkey {} a drawer of a desk, indoor scene",
    "A photo of a baby {} a drawer of a desk, indoor scene",
    "A photo of a bear {} a drawer of a desk, indoor scene",
    "A photo of a panda {} a drawer of a desk, indoor scene",
    "A photo of a squrrirel {} a drawer of a desk, indoor scene",
    "A photo of David Beckham {} a drawer of a desk, indoor scene",
    "A photo of Michael Jackson {} a drawer of a desk, indoor scene",
    "A photo of Taylor Swift {} a drawer of a desk, indoor scene",

    "A photo of a boy {} a drawer of a dresser, indoor scene",
    "A photo of a girl {} a drawer of a dresser, indoor scene",
    "A photo of a grandpa {} a drawer of a dresser, indoor scene",
    "A photo of a monkey {} a drawer of a dresser, indoor scene",
    "A photo of a baby {} a drawer of a dresser, indoor scene",
    "A photo of a bear {} a drawer of a dresser, indoor scene",
    "A photo of a panda {} a drawer of a dresser, indoor scene",
    "A photo of a squrrirel {} a drawer of a dresser, indoor scene",
    "A photo of David Beckham {} a drawer of a dresser, indoor scene",
    "A photo of Michael Jackson {} a drawer of a dresser, indoor scene",
    "A photo of Taylor Swift {} a drawer of a dresser, indoor scene",

    "A photo of a boy {} a drawer of a tool chest, indoor scene",
    "A photo of a girl {} a drawer of a tool chest, indoor scene",
    "A photo of a grandpa {} a drawer of a tool chest, indoor scene",
    "A photo of a monkey {} a drawer of a tool chest, indoor scene",
    "A photo of a baby {} a drawer of a tool chest, indoor scene",
    "A photo of a bear {} a drawer of a tool chest, indoor scene",
    "A photo of a panda {} a drawer of a tool chest, indoor scene",
    "A photo of a squrrirel {} a drawer of a tool chest, indoor scene",
    "A photo of David Beckham {} a drawer of a tool chest, indoor scene",
    "A photo of Michael Jackson {} a drawer of a tool chest, indoor scene",
    "A photo of Taylor Swift {} a drawer of a tool chest, indoor scene",

    "A photo of a boy {} a drawer, indoor scene",
    "A photo of a girl {} a drawer, indoor scene",
    "A photo of a grandpa {} a drawer, indoor scene",
    "A photo of a monkey {} a drawer, indoor scene",
    "A photo of a baby {} a drawer, indoor scene",
    "A photo of a bear {} a drawer, indoor scene",
    "A photo of a panda {} a drawer, indoor scene",
    "A photo of a squrrirel {} a drawer, indoor scene",
    "A photo of David Beckham {} a drawer, indoor scene",
    "A photo of Michael Jackson {} a drawer, indoor scene",
    "A photo of Taylor Swift {} a drawer, indoor scene",
    ],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],

    "sd-open-templates":
    ["A photo of Yann Lecun open the door of a refrigerator",
    "A photo of Bruno Mars open the door of a refrigerator",
    "A photo of David Beckham open the door of a refrigerator",
    "A photo of Lenardo Decaprio open the door of a refrigerator",
    "A photo of Donald Trump open the door of a refrigerator",
    "A photo of Lionel Messi open the door of a refrigerator",
    "A photo of spiderman open the door of a refrigerator",
    "A photo of batman open the door of a refrigerator",
    "A photo of superman open the door of a refrigerator",
    "A photo of a rabbit open the door of a refrigerator",
    "A photo of a panda open the door of a refrigerator",
    "A photo of a bear open the door of a refrigerator",
    "A photo of a monkey open the door of a refrigerator",
    "A photo of an elephant open the door of a refrigerator",
    "A photo of a baby open the door of a refrigerator",
    "A photo of a girl open the door of a refrigerator",
    "A photo of a boy open the door of a refrigerator",
    "A photo of a woman open the door of a refrigerator",
    "A photo of a young man open the door of a refrigerator",

    "A photo of Yann Lecun open the door of a safebox",
    "A photo of Bruno Mars open the door of a safebox",
    "A photo of David Beckham open the door of a safebox",
    "A photo of Lenardo Decaprio open the door of a safebox",
    "A photo of Donald Trump open the door of a safebox",
    "A photo of Lionel Messi open the door of a safebox",
    "A photo of spiderman open the door of a safebox",
    "A photo of batman open the door of a safebox",
    "A photo of superman open the door of a safebox",
    "A photo of a rabbit open the door of a safebox",
    "A photo of a panda open the door of a safebox",
    "A photo of a bear open the door of a safebox",
    "A photo of a monkey open the door of a safebox",
    "A photo of an elephant open the door of a safebox",
    "A photo of a baby open the door of a safebox",
    "A photo of a girl open the door of a safebox",
    "A photo of a boy open the door of a safebox",
    "A photo of a woman open the door of a safebox",
    "A photo of a young man open the door of a safebox",

    "A photo of Yann Lecun open the door of a cabinet",
    "A photo of Bruno Mars open the door of a cabinet",
    "A photo of David Beckham open the door of a cabinet",
    "A photo of Lenardo Decaprio open the door of a cabinet",
    "A photo of Donald Trump open the door of a cabinet",
    "A photo of Lionel Messi open the door of a cabinet",
    "A photo of spiderman open the door of a cabinet",
    "A photo of batman open the door of a cabinet",
    "A photo of superman open the door of a cabinet",
    "A photo of a rabbit open the door of a cabinet",
    "A photo of a panda open the door of a cabinet",
    "A photo of a bear open the door of a cabinet",
    "A photo of a monkey open the door of a cabinet",
    "A photo of an elephant open the door of a cabinet",
    "A photo of a baby open the door of a cabinet",
    "A photo of a girl open the door of a cabinet",
    "A photo of a boy open the door of a cabinet",
    "A photo of a woman open the door of a cabinet",
    "A photo of a young man open the door of a cabinet",

    "A photo of Yann Lecun open the door of a plane",
    "A photo of Bruno Mars open the door of a plane",
    "A photo of David Beckham open the door of a plane",
    "A photo of Lenardo Decaprio open the door of a plane",
    "A photo of Donald Trump open the door of a plane",
    "A photo of Lionel Messi open the door of a plane",
    "A photo of spiderman open the door of a plane",
    "A photo of batman open the door of a plane",
    "A photo of superman open the door of a plane",
    "A photo of a rabbit open the door of a plane",
    "A photo of a panda open the door of a plane",
    "A photo of a bear open the door of a plane",
    "A photo of a monkey open the door of a plane",
    "A photo of an elephant open the door of a plane",
    "A photo of a baby open the door of a plane",
    "A photo of a girl open the door of a plane",
    "A photo of a boy open the door of a plane",
    "A photo of a woman open the door of a plane",
    "A photo of a young man open the door of a plane",

    "A photo of Yann Lecun open the door of a room",
    "A photo of Bruno Mars open the door of a room",
    "A photo of David Beckham open the door of a room",
    "A photo of Lenardo Decaprio open the door of a room",
    "A photo of Donald Trump open the door of a room",
    "A photo of Lionel Messi open the door of a room",
    "A photo of spiderman open the door of a room",
    "A photo of batman open the door of a room",
    "A photo of superman open the door of a room",
    "A photo of a rabbit open the door of a room",
    "A photo of a panda open the door of a room",
    "A photo of a bear open the door of a room",
    "A photo of a monkey open the door of a room",
    "A photo of an elephant open the door of a room",
    "A photo of a baby open the door of a room",
    "A photo of a girl open the door of a room",
    "A photo of a boy open the door of a room",
    "A photo of a woman open the door of a room",
    "A photo of a young man open the door of a room",],        

    "sd-pull-drawer-templates":
    [
    "A photo of a robot pull out a drawer of a cabinet",
    "A photo of a robot arm pull out a drawer of a cabinet",
    "A photo of a boy pull out a drawer of a cabinet",
    "A photo of a girl pull out a drawer of a cabinet",
    "A photo of a grandpa pull out a drawer of a cabinet",
    "A photo of a monkey pull out a drawer of a cabinet",
    "A photo of a baby pull out a drawer of a cabinet",
    "A photo of Donald Trump pull out a drawer of a cabinet",
    
    
    "A photo of a robot pull out a drawer of a desk",
    "A photo of a robot arm pull out a drawer of a desk",
    "A photo of a boy pull out a drawer of a desk",
    "A photo of a girl pull out a drawer of a desk",
    "A photo of a grandpa pull out a drawer of a desk",
    "A photo of a monkey pull out a drawer of a desk",
    "A photo of a baby pull out a drawer of a desk",
    "A photo of Donald Trump pull out a drawer of a desk",
    
    "A photo of a rabit pull out a drawer of a box",
    "A photo of a lady pull out a drawer of a box",
    "A photo of Michael Jackson pull out a drawer of a box",
    "A photo of Taylor Swift pull out a drawer of a box",
    "A photo of a panda pull out a drawer of a box",
    "A photo of a cleaner pull out a drawer of a box",
    "A photo of a bird pull out a drawer of a box",
    "A photo of a cat pull out a drawer of a box",
    "A photo of a otter pull out a drawer of a box",],
    
    "some_special_templates":[
    "A photo of a lady pull out a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson pull out a microphone, on a floor",
    "A photo of an otter pull out a fish in the water, by the lake",
    "A photo of a panda pull out a hat, in the forest",
        ],
    
    "simple_pull_door_templates-v519":
    [
    "A photo of Yann Lecun {} the door of a refrigerator",
    "A photo of Bruno Mars {} the door of a refrigerator",
    "A photo of David Beckham {} the door of a refrigerator",
    "A photo of Lenardo Decaprio {} the door of a refrigerator",
    "A photo of Donald Trump {} the door of a refrigerator",
    "A photo of Lionel Messi {} the door of a refrigerator",
    "A photo of spiderman {} the door of a refrigerator",
    "A photo of batman {} the door of a refrigerator",
    "A photo of superman {} the door of a refrigerator",
    "A photo of a rabbit {} the door of a refrigerator",
    "A photo of a panda {} the door of a refrigerator",
    "A photo of a bear {} the door of a refrigerator",
    "A photo of a monkey {} the door of a refrigerator",
    "A photo of an elephant {} the door of a refrigerator",
    "A photo of a baby {} the door of a refrigerator",
    "A photo of a girl {} the door of a refrigerator",
    "A photo of a boy {} the door of a refrigerator",
    "A photo of a woman {} the door of a refrigerator",
    "A photo of a young man {} the door of a refrigerator",

    "A photo of Yann Lecun {} the door of a safebox",
    "A photo of Bruno Mars {} the door of a safebox",
    "A photo of David Beckham {} the door of a safebox",
    "A photo of Lenardo Decaprio {} the door of a safebox",
    "A photo of Donald Trump {} the door of a safebox",
    "A photo of Lionel Messi {} the door of a safebox",
    "A photo of spiderman {} the door of a safebox",
    "A photo of batman {} the door of a safebox",
    "A photo of superman {} the door of a safebox",
    "A photo of a rabbit {} the door of a safebox",
    "A photo of a panda {} the door of a safebox",
    "A photo of a bear {} the door of a safebox",
    "A photo of a monkey {} the door of a safebox",
    "A photo of an elephant {} the door of a safebox",
    "A photo of a baby {} the door of a safebox",
    "A photo of a girl {} the door of a safebox",
    "A photo of a boy {} the door of a safebox",
    "A photo of a woman {} the door of a safebox",
    "A photo of a young man {} the door of a safebox",

    "A photo of Yann Lecun {} the door of a cabinet",
    "A photo of Bruno Mars {} the door of a cabinet",
    "A photo of David Beckham {} the door of a cabinet",
    "A photo of Lenardo Decaprio {} the door of a cabinet",
    "A photo of Donald Trump {} the door of a cabinet",
    "A photo of Lionel Messi {} the door of a cabinet",
    "A photo of spiderman {} the door of a cabinet",
    "A photo of batman {} the door of a cabinet",
    "A photo of superman {} the door of a cabinet",
    "A photo of a rabbit {} the door of a cabinet",
    "A photo of a panda {} the door of a cabinet",
    "A photo of a bear {} the door of a cabinet",
    "A photo of a monkey {} the door of a cabinet",
    "A photo of an elephant {} the door of a cabinet",
    "A photo of a baby {} the door of a cabinet",
    "A photo of a girl {} the door of a cabinet",
    "A photo of a boy {} the door of a cabinet",
    "A photo of a woman {} the door of a cabinet",
    "A photo of a young man {} the door of a cabinet",

    "A photo of Yann Lecun {} the door of a plane",
    "A photo of Bruno Mars {} the door of a plane",
    "A photo of David Beckham {} the door of a plane",
    "A photo of Lenardo Decaprio {} the door of a plane",
    "A photo of Donald Trump {} the door of a plane",
    "A photo of Lionel Messi {} the door of a plane",
    "A photo of spiderman {} the door of a plane",
    "A photo of batman {} the door of a plane",
    "A photo of superman {} the door of a plane",
    "A photo of a rabbit {} the door of a plane",
    "A photo of a panda {} the door of a plane",
    "A photo of a bear {} the door of a plane",
    "A photo of a monkey {} the door of a plane",
    "A photo of an elephant {} the door of a plane",
    "A photo of a baby {} the door of a plane",
    "A photo of a girl {} the door of a plane",
    "A photo of a boy {} the door of a plane",
    "A photo of a woman {} the door of a plane",
    "A photo of a young man {} the door of a plane",

    "A photo of Yann Lecun {} the door of a room",
    "A photo of Bruno Mars {} the door of a room",
    "A photo of David Beckham {} the door of a room",
    "A photo of Lenardo Decaprio {} the door of a room",
    "A photo of Donald Trump {} the door of a room",
    "A photo of Lionel Messi {} the door of a room",
    "A photo of spiderman {} the door of a room",
    "A photo of batman {} the door of a room",
    "A photo of superman {} the door of a room",
    "A photo of a rabbit {} the door of a room",
    "A photo of a panda {} the door of a room",
    "A photo of a bear {} the door of a room",
    "A photo of a monkey {} the door of a room",
    "A photo of an elephant {} the door of a room",
    "A photo of a baby {} the door of a room",
    "A photo of a girl {} the door of a room",
    "A photo of a boy {} the door of a room",
    "A photo of a woman {} the door of a room",
    "A photo of a young man {} the door of a room",
    ],



    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],


    "sd_pull_door_templates":
    [
    "A photo of a robot open the door of a refrigerator",
    "A photo of a robot arm open the door of a refrigerator",
    "A photo of a boy open the door of a refrigerator",
    "A photo of a girl open the door of a refrigerator",
    "A photo of a grandpa open the door of a refrigerator",
    "A photo of a monkey open the door of a refrigerator",
    "A photo of a baby open the door of a refrigerator",
    "A photo of Donald Trump open the door of a refrigerator",
    
    
    "A photo of a robot open the door of a safebox",
    "A photo of a robot arm open a door of a safebox",
    "A photo of a boy open a door of a safebox",
    "A photo of a girl open a door of a safebox",
    "A photo of a grandpa open a door of a safebox",
    "A photo of a monkey open a door of a safebox",
    "A photo of a baby open a door of a safebox",
    "A photo of Donald Trump open a door of a safebox",
    
    "A photo of a rabit open a door of a house",
    "A photo of a lady open a door of a house",
    "A photo of Michael Jackson open a door of a house",
    "A photo of Taylor Swift open a door of a house",
    "A photo of a panda open a door of a house",
    "A photo of a cleaner open a ddoor of a house",
    "A photo of a bird open a door of a house",
    "A photo of a cat open a door of a house",
    "A photo of a otter open a door of a house",],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],
    # please put your customized templates from here
     "sd_pull_door_templates_v2":
    [
    "A photo of a boy open the door of a refrigerator",
    "A photo of a girl open the door of a refrigerator",
    "A photo of a grandpa open the door of a refrigerator",
    "A photo of a monkey open the door of a refrigerator",
    "A photo of a baby open the door of a refrigerator",
    "A photo of Donald Trump open the door of a refrigerator",
    
    "A photo of a lady open a door of a bedroom",
    "A photo of Michael Jackson open a door of a bedroom",
    "A photo of Taylor Swift open a door of a bedroom",
    "A photo of a panda open a door of a bedroom",
    "A photo of a cleaner open a ddoor of a bedroom",
    "A photo of a bird open a door of a bedroom",
    "A photo of a cat open a door of a bedroom",
    
    "A photo of a lady open a door of a cabinet",
    "A photo of Michael Jackson open a door of a cabinet",
    "A photo of Taylor Swift open a door of a cabinet",
    "A photo of a panda open a door of a cabinet",
    "A photo of a cleaner open a ddoor of a cabinet",
    ],
    
     "sd_pull_door_templates_v3":
    [
    "A photo of a lady open a door of a cabinet. About 30 degrees, indoor scene, front view, the lady is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    "A photo of a lady open a door of a cabinet. About 30 degrees, indoor scene, left side view, the lady is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    
    "A photo of Michael Jackson open a door of a cabinet. About 90 degrees, indoor scene, front view, Michael Jackson is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    "A photo of Michael Jackson open a door of a cabinet. About 90 degrees, indoor scene, left side view, Michael Jackson is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    
    "A photo of a boy open a door of a cabinet. About 30 degrees, indoor scene, front view, the boy is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    "A photo of a boy open a door of a cabinet. About 30 degrees, indoor scene, left side view, the boy is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    ],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],

    "reversion_test":
    [
    "An elephant {} a strawberry on a table.",
    "A flamingo{} a strawberry on a table.",
    "A man {} a strawberry on a table.",
    "An elephant {} a strawberry.",
    "A flamingo{} a strawberry.",
    "A man {} a strawberry.",
    "elephant {} a strawberry.",
    "flamingo{} a strawberry.",
    "man {} a strawberry.",
    "elephant {} strawberry.",
    "flamingo{} strawberry.",
    "man {} strawberry.",
    ],

    "reversion_test_v2":
    [
    "A photo of a young man {} a bottle on table",
    "A photo of a young man {} a glass cup on table",
    ],

    "simple_push_add":
    [
    "A photo of dung beetle {} a stone",
    "A photo of dung beetle {} a glass ball",
    "A photo of dung beetle {} a little ball",
    "A photo of dung beetle {} a little pebble",
    "A photo of dung beetle {} a bottle",
    ],

    "simple_push_add_v2":
    [
    "A photo of cleaner {} a dust bin",
    "A photo of cleaner {} a recycle bin",
    "A photo of repairer {} a car",
    "A photo of repairer {} a destroyed car",
    "A photo of porter {} a large box",
    "A photo of porter {} a flat car",
    ],

    "simple_push_add_v3":
    [
    "A photo of Super Mario {} a cube",
    "A photo of kid {} a cube",
    "A photo of a bear {} a cube",
    "A photo of woman {} a trolley",
    "A photo of kid {} a wheelchair",
    "A photo of a bear {} a wheelchair",
    "A photo of a tiger {} a wheelchair",
    "A photo of a waiter {} a serving trolley",
    ],

    "simple_push_add_v4":
    [
    "A photo of woman {} a trolley in a supermarket",
    ],

    "simple_push_add_v5":
    [
    "A photo of superman{} a stone",
    "A photo of superman{} a spaceship",
    "A photo of superman{} a meteorite",
    "A photo of superman{} the earth",
    "A photo of superman{} the moon",
    "A photo of superman{} a tree",
    ],

    "simple_move_bucket_v4":
    [
    "A photo of a bear {} a pot",
    "A photo of a bear {} a honey pot",
    "A photo of a girl {} a box of toys",
    "A photo of a girl {} a box of clothes",
    "A photo of a teacher {} a stack of books",
    "A photo of a studnet {} a books",
    ],


    "simple_push_chair_templates-v520":
    [
    "A photo of Yann Lecun {} desk",
    "A photo of Bruno Mars {} desk",
    "A photo of David Beckham {} desk",
    "A photo of Lenardo Decaprio {} desk",
    "A photo of Donald Trump {} desk",
    "A photo of Lionel Messi {} desk",
    "A photo of spiderman {} desk",
    "A photo of batman {} desk",
    "A photo of superman {} desk",
    "A photo of a rabbit {} desk",
    "A photo of a panda {} desk",
    "A photo of a bear {} desk",
    "A photo of a monkey {} desk",
    "A photo of an elephant {} desk",
    "A photo of a baby {} desk",
    "A photo of a girl {} desk",
    "A photo of a boy {} desk",
    "A photo of a woman {} desk",
    "A photo of a young man {} desk",

    "A photo of Yann Lecun {} a big case",
    "A photo of Bruno Mars {} a big case",
    "A photo of David Beckham {} a big case",
    "A photo of Lenardo Decaprio {} a big case",
    "A photo of Donald Trump {} a big case",
    "A photo of Lionel Messi {} a big case",
    "A photo of spiderman {} a big case",
    "A photo of batman {} a big case",
    "A photo of superman {} a big case",
    "A photo of a rabbit {} a big case",
    "A photo of a panda {} a big case",
    "A photo of a bear {} a big case",
    "A photo of a monkey {} a big case",
    "A photo of an elephant {} a big case",
    "A photo of a baby {} a big case",
    "A photo of a girl {} a big case",
    "A photo of a boy {} a big case",
    "A photo of a woman {} a big case",
    "A photo of a young man {} a big case",

    "A photo of Yann Lecun {} a bicyle",
    "A photo of Bruno Mars {} a bicyle",
    "A photo of David Beckham {} a bicyle",
    "A photo of Lenardo Decaprio {} a bicyle",
    "A photo of Donald Trump {} a bicyle",
    "A photo of Lionel Messi {} a bicyle",
    "A photo of spiderman {} a bicyle",
    "A photo of batman {} a bicyle",
    "A photo of superman {} a bicyle",
    "A photo of a rabbit {} a bicyle",
    "A photo of a panda {} a bicyle",
    "A photo of a bear {} a bicyle",
    "A photo of a monkey {} a bicyle",
    "A photo of an elephant {} a bicyle",
    "A photo of a baby {} a bicyle",
    "A photo of a girl {} a bicyle",
    "A photo of a boy {} a bicyle",
    "A photo of a woman {} a bicyle",
    "A photo of a young man {} a bicyle",

    "A photo of Yann Lecun {} a truck",
    "A photo of Bruno Mars {} a truck",
    "A photo of David Beckham {} a truck",
    "A photo of Lenardo Decaprio {} a truck",
    "A photo of Donald Trump {} a truck",
    "A photo of Lionel Messi {} a truck",
    "A photo of spiderman {} a truck",
    "A photo of batman {} a truck",
    "A photo of superman {} a truck",
    "A photo of a rabbit {} a truck",
    "A photo of a panda {} a truck",
    "A photo of a bear {} a truck",
    "A photo of a monkey {} a truck",
    "A photo of an elephant {} a truck",
    "A photo of a baby {} a truck",
    "A photo of a girl {} a truck",
    "A photo of a boy {} a truck",
    "A photo of a woman {} a truck",
    "A photo of a young man {} a truck",

    "A photo of Yann Lecun {} a big stone",
    "A photo of Bruno Mars {} a big stone",
    "A photo of David Beckham {} a big stone",
    "A photo of Lenardo Decaprio {} a big stone",
    "A photo of Donald Trump {} a big stone",
    "A photo of Lionel Messi {} a big stone",
    "A photo of spiderman {} a big stone",
    "A photo of batman {} a big stone",
    "A photo of superman {} a big stone",
    "A photo of a rabbit {} a big stone",
    "A photo of a panda {} a big stone",
    "A photo of a bear {} a big stone",
    "A photo of a monkey {} a big stone",
    "A photo of an elephant {} a big stone",
    "A photo of a baby {} a big stone",
    "A photo of a girl {} a big stone",
    "A photo of a boy {} a big stone",
    "A photo of a woman {} a big stone",
    "A photo of a young man {} a big stone",
    ],

    "simple_move_bucket_templates-v520":
    [
    "A photo of Yann Lecun {} desk",
    "A photo of Bruno Mars {} desk",
    "A photo of David Beckham {} desk",
    "A photo of Lenardo Decaprio {} desk",
    "A photo of Donald Trump {} desk",
    "A photo of Lionel Messi {} desk",
    "A photo of spiderman {} desk",
    "A photo of batman {} desk",
    "A photo of superman {} desk",
    "A photo of a rabbit {} desk",
    "A photo of a panda {} desk",
    "A photo of a bear {} desk",
    "A photo of a monkey {} desk",
    "A photo of an elephant {} desk",
    "A photo of a baby {} desk",
    "A photo of a girl {} desk",
    "A photo of a boy {} desk",
    "A photo of a woman {} desk",
    "A photo of a young man {} desk",

    "A photo of Yann Lecun {} a small case",
    "A photo of Bruno Mars {} a small case",
    "A photo of David Beckham {} a small case",
    "A photo of Lenardo Decaprio {} a small case",
    "A photo of Donald Trump {} a small case",
    "A photo of Lionel Messi {} a small case",
    "A photo of spiderman {} a small case",
    "A photo of batman {} a small case",
    "A photo of superman {} a small case",
    "A photo of a rabbit {} a small case",
    "A photo of a panda {} a small case",
    "A photo of a bear {} a small case",
    "A photo of a monkey {} a small case",
    "A photo of an elephant {} a small case",
    "A photo of a baby {} a small case",
    "A photo of a girl {} a small case",
    "A photo of a boy {} a small case",
    "A photo of a woman {} a small case",
    "A photo of a young man {} a small case",

    "A photo of Yann Lecun {} a vase",
    "A photo of Bruno Mars {} a vase",
    "A photo of David Beckham {} a vase",
    "A photo of Lenardo Decaprio {} a vase",
    "A photo of Donald Trump {} a vase",
    "A photo of Lionel Messi {} a vase",
    "A photo of spiderman {} a vase",
    "A photo of batman {} a vase",
    "A photo of superman {} a vase",
    "A photo of a rabbit {} a vase",
    "A photo of a panda {} a vase",
    "A photo of a bear {} a vase",
    "A photo of a monkey {} a vase",
    "A photo of an elephant {} a vase",
    "A photo of a baby {} a vase",
    "A photo of a girl {} a vase",
    "A photo of a boy {} a vase",
    "A photo of a woman {} a vase",
    "A photo of a young man {} a vase",

    "A photo of Yann Lecun {} a television",
    "A photo of Bruno Mars {} a television",
    "A photo of David Beckham {} a television",
    "A photo of Lenardo Decaprio {} a television",
    "A photo of Donald Trump {} a television",
    "A photo of Lionel Messi {} a television",
    "A photo of spiderman {} a television",
    "A photo of batman {} a television",
    "A photo of superman {} a television",
    "A photo of a rabbit {} a television",
    "A photo of a panda {} a television",
    "A photo of a bear {} a television",
    "A photo of a monkey {} a television",
    "A photo of an elephant {} a television",
    "A photo of a baby {} a television",
    "A photo of a girl {} a television",
    "A photo of a boy {} a television",
    "A photo of a woman {} a television",
    "A photo of a young man {} a television",

    "A photo of Yann Lecun {} a doll",
    "A photo of Bruno Mars {} a doll",
    "A photo of David Beckham {} a doll",
    "A photo of Lenardo Decaprio {} a doll",
    "A photo of Donald Trump {} a doll",
    "A photo of Lionel Messi {} a doll",
    "A photo of spiderman {} a doll",
    "A photo of batman {} a doll",
    "A photo of superman {} a doll",
    "A photo of a rabbit {} a doll",
    "A photo of a panda {} a doll",
    "A photo of a bear {} a doll",
    "A photo of a monkey {} a doll",
    "A photo of an elephant {} a doll",
    "A photo of a baby {} a doll",
    "A photo of a girl {} a doll",
    "A photo of a boy {} a doll",
    "A photo of a woman {} a doll",
    "A photo of a young man {} a doll",
    ],

    "simple_plug_in_templates-v520":
    [
    "A photo of Yann Lecun {} power charger into a socket",
    "A photo of Bruno Mars {} power charger into a socket",
    "A photo of David Beckham {} power charger into a socket",
    "A photo of Lenardo Decaprio {} power charger into a socket",
    "A photo of Donald Trump {} power charger into a socket",
    "A photo of Lionel Messi {} power charger into a socket",
    "A photo of spiderman {} power charger into a socket",
    "A photo of batman {} power charger into a socket",
    "A photo of superman {} power charger into a socket",
    "A photo of a baby {} power charger into a socket",
    "A photo of a girl {} power charger into a socket",
    "A photo of a boy {} power charger into a socket",
    "A photo of a woman {} power charger into a socket",
    "A photo of a young man {} power charger into a socket",
    "A photo of a pig {} power charger into a socket",
    "A photo of a squirrel {} power charger into a socket",
    "A photo of an octopus {} power charger into a socket",
    "A photo of a tiger {} power charger into a socket",

    "A photo of Yann Lecun {} a coin into a saving pot",
    "A photo of Bruno Mars {} a coin into a saving pot",
    "A photo of David Beckham {} a coin into a saving pot",
    "A photo of Lenardo Decaprio {} a coin into a saving pot",
    "A photo of Donald Trump {} a coin into a saving pot",
    "A photo of Lionel Messi {} a coin into a saving pot",
    "A photo of spiderman {} a coin into a saving pot",
    "A photo of batman {} a coin into a saving pot",
    "A photo of superman {} a coin into a saving pot",
    "A photo of a baby {} a coin into a saving pot",
    "A photo of a girl {} a coin into a saving pot",
    "A photo of a boy {} a coin into a saving pot",
    "A photo of a woman {} a coin into a saving pot",
    "A photo of a young man {} a coin into a saving pot",
    "A photo of a pig {} a coin into a saving pot",
    "A photo of a squirrel {} a coin into a saving pot",
    "A photo of an octopus {} a coin into a saving pot",
    "A photo of a tiger {} a coin into a saving pot",
    "A photo of a dog {} a coin into a saving pot",

    "A photo of Yann Lecun {} a bank card into ATM",
    "A photo of Bruno Mars {} a bank card into ATM",
    "A photo of David Beckham {} a bank card into ATM",
    "A photo of Lenardo Decaprio {} a bank card into ATM",
    "A photo of Donald Trump {} a bank card into ATM",
    "A photo of Lionel Messi {} a bank card into ATM",
    "A photo of spiderman {} a bank card into ATM",
    "A photo of batman {} a bank card into ATM",
    "A photo of superman {} a bank card into ATM",
    "A photo of a baby {} a bank card into ATM",
    "A photo of a girl {} a bank card into ATM",
    "A photo of a boy {} a bank card into ATM",
    "A photo of a woman {} a bank card into ATM",
    "A photo of a young man {} a bank card into ATM",
    "A photo of a pig {} a bank card into ATM",
    "A photo of a squirrel {} a bank card into ATM",
    "A photo of an octopus {} a bank card into ATM",
    "A photo of a tiger {} a bank card into ATM",
    "A photo of a dog {} a bank card into ATM",
    

    "A photo of Yann Lecun {} a charger into a phone",
    "A photo of Bruno Mars {} a charger into a phone",
    "A photo of David Beckham {} a charger into a phone",
    "A photo of Lionel Messi {} a charger into a phone",
    "A photo of spiderman {} a charger into a phone",
    "A photo of batman {} a charger into a phone",
    "A photo of superman {} a charger into a phone",
    "A photo of a baby {} a charger into a phone",
    "A photo of a girl {} a charger into a phone",
    "A photo of a boy {} a charger into a phone",
    "A photo of a woman {} a charger into a phone",
    "A photo of a young man {} a charger into a phone",
    "A photo of a pig {} a charger into a phone",
    "A photo of a squirrel {} a charger into a phone",
    "A photo of an octopus {} a charger into a phone",
    "A photo of a tiger {} a charger into a phone",
    "A photo of a dog {} a charger into a phone",
    

    "A photo of Yann Lecun {} a screw spike into a hole",
    "A photo of Bruno Mars {} a screw spike into a hole",
    "A photo of David Beckham {} a screw spike into a hole",
    "A photo of Lionel Messi {} a screw spike into a hole",
    "A photo of spiderman {} a screw spike into a hole",
    "A photo of batman {} a screw spike into a hole",
    "A photo of superman {} a screw spike into a hole",
    "A photo of a baby {} a screw spike into a hole",
    "A photo of a girl {} a screw spike into a hole",
    "A photo of a boy {} a screw spike into a hole",
    "A photo of a woman {} a screw spike into a hole",
    "A photo of a young man {} a screw spike into a hole",
    "A photo of a pig {} a screw spike into a hole",
    "A photo of a squirrel {} a screw spike into a hole",
    "A photo of an octopus {} a screw spike into a hole",
    "A photo of a tiger {} a screw spike into a hole",
    "A photo of a dog {} a screw spike into a hole",
    ],

     "simple_plug_in_add-v1":
    [
    "A photo of a squirrel {} several coins into a hole",
    "A photo of a squirrel {} several pine nuts into a hole",
    "A photo of a squirrel {} several biscuits into a hole",
    "A photo of a squirrel {} several of leafs into a hole",
    "A photo of a squirrel {} several of candy into a hole",
    "A photo of a squirrel {} coins into a hole",
    "A photo of a squirrel {} pinenuts into a hole",
    "A photo of a squirrel {} biscuits into a hole",
    "A photo of a squirrel {} leafs into a hole",
    "A photo of a squirrel {} candy into a hole",
    ],

    "simple_pull_door_beckhame":
    [
    "A photo of David Beckham {} the door of a room",
    ],

    "simple_sd_compare_actions":
    [
    "A photo of Super Mario move a cube",
    ],

    "simple_push_reversion-v522":
    [
        "A photo of a tiger {} a wheelchair",
    ],

    "simple_move_reversion-v522":
    [
        "A photo of a teacher {} a stack of books",
    ],

    "simple_drawer_reversion-v522":
    [
        "A photo of a panda {} a drawer of the box",
    ],
    "ablation_on_move_preps":
    ["A photo of Super Mario {} a cube",
     "A photo of a teacher {} a stack of books",
     "A photo of Leonardo Dicaprio {} a vase",],
}
